# Generated by Django 5.0.4 on 2024-04-23 10:44

import network.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(network.models.Post._get_unknown_user), related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
